#define NUMBER                          1
#define IDEN                            2
#define ASSIGN                          3
#define PEQ                             4
#define SEQ                             5
#define MEQ                             6
#define DEQ                             7
#define OR                              8
#define AND                             9
#define EQ                             10
#define NEQ                            11
#define BTHAN                          12
#define LTHAN                          13
#define LEQ                            14
#define BEQ                            15
#define ADD                            16
#define SUB                            17
#define MUL                            18
#define DIV                            19
#define LPAREN                         20
#define RPAREN                         21
#define INT                            22
#define SEMICOLON                      23
#define IF                             24
#define ELSE                           25
#define WHILE                          26
#define DO                             27
#define FOR                            28
#define LBRACKET                       29
#define RBRACKET                       30
